name = "SeisMonitoring"
uuid = "d0d3aec2-4138-4376-b1ce-a7d204193698"
authors = ["Kurama Okubo"]
version = "0.1.0"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
