name: Documentation

on:
  push:
    branches:
      - master # update to match your development branch (master, main, dev, trunk, ...)
      - develop
      - dev_parallel_modified
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg;Pkg.update(); Pkg.add(name="Documenter", version="0.27"); Pkg.add(PackageSpec(name="SeisIO", version="1.2.1")); Pkg.add(PackageSpec(name="SeisNoise", version="0.5.3")); Pkg.add(url="https://github.com/kura-okubo/SeisDvv.jl"); Pkg.add(url="https://github.com/kura-okubo/SeisMonitoring.jl"); Pkg.instantiate();'
        
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
