name: Run tests

on: 
  push:
    branches:
      - master
      - dev_beforeupdate@0.2.0
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.update(); Pkg.add(PackageSpec(name="SeisIO", version="1.2.1")); Pkg.add(PackageSpec(name="SeisNoise", version="0.5.3")); Pkg.add(url="https://github.com/kura-okubo/SeisDvv.jl"); Pkg.add(url="https://github.com/kura-okubo/SeisMonitoring.jl"); Pkg.add(["Plots", "JLD2", "DataStructures", "Dates", "CSV", "DataFrames", "Interpolations"]); Pkg.instantiate(); Pkg.resolve(); Pkg.update();'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        # with:
        #   annotate: true
