name: Run tests

on: 
  push:
    branches:
      - master
      - dev_beforeupdate@0.2.0
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      # We test the latest Julia v1.x, nightly in 64bit PC on ubuntu-latest and macOS-latest
      matrix:
        julia-version: ['1', 'nightly']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]

    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: julia --color=yes --project="@." -e 'using Pkg; ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; Pkg.Registry.add("General"); Pkg.develop(url="https://github.com/kura-okubo/SeisDvv.jl"); Pkg.instantiate(); Pkg.resolve(); Pkg.build()'
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        # with:
        #   annotate: true
